"""
create_star_obj.py
==================
Generates a 6-arm star-prism OBJ that matches the existing Star600M geometry.
The star is defined in the XZ plane and extruded along Y.

   arms    = 6
   R_outer = outer tip radius (mm)
   R_inner = inner concave radius (mm)
   height  = extrusion height (mm)

The shape is designed so its bounding-sphere radius matches the
existing Star600M.json nominalRadius ~ 0.447 mm.

Usage
-----
  python create_star_obj.py [output.obj] [--arms N] [--outer R]
                            [--inner R] [--height H]

Defaults produce a 6-arm star with nominalRadius ~ 0.45 mm.
"""
import argparse
import math
from pathlib import Path


def build_star_prism(
    arms: int = 6,
    r_outer: float = 0.44,
    r_inner: float = 0.20,
    height: float = 0.30,
):
    """
    Build a star-prism mesh.

    Returns (verts [(x,y,z)...], faces [(a,b,c)...]) zero-indexed.

    The star silhouette sits in the XZ plane, extruded height/2 in Y.
    """
    n = arms * 2          # total profile points (alternating outer/inner)
    half_h = height / 2.0

    # Build 2D star profile in XZ
    profile = []
    for i in range(n):
        angle = math.pi / arms * i   # steps of pi/arms
        r = r_outer if i % 2 == 0 else r_inner
        profile.append((r * math.cos(angle), r * math.sin(angle)))  # (x, z)

    # 3D vertices: bottom ring (y=-half_h) then top ring (y=+half_h)
    # then bottom centre and top centre
    verts = []
    for (x, z) in profile:
        verts.append((x, -half_h, z))   # bottom ring [0 .. n-1]
    for (x, z) in profile:
        verts.append((x, +half_h, z))   # top ring    [n .. 2n-1]
    bot_centre = len(verts); verts.append((0.0, -half_h, 0.0))
    top_centre = len(verts); verts.append((0.0, +half_h, 0.0))

    faces = []

    # Bottom cap (fan triangulation, pointing down -> normal -Y)
    for i in range(n):
        a = i
        b = (i + 1) % n
        faces.append((bot_centre, b, a))   # CCW seen from below

    # Top cap (fan triangulation, pointing up -> normal +Y)
    for i in range(n):
        a = n + i
        b = n + (i + 1) % n
        faces.append((top_centre, a, b))

    # Side quads -> 2 triangles each
    for i in range(n):
        b0 = i
        b1 = (i + 1) % n
        t0 = n + i
        t1 = n + (i + 1) % n
        # quad b0,b1,t1,t0 -> two CCW tris (seen from outside)
        faces.append((b0, t0, t1))
        faces.append((b0, t1, b1))

    return verts, faces


def save_obj(path, verts, faces):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Star prism OBJ  generated by create_star_obj.py\n")
        for x, y, z in verts:
            fh.write(f"v {x:.9g} {y:.9g} {z:.9g}\n")
        for a, b, c in faces:
            fh.write(f"f {a+1} {b+1} {c+1}\n")
    print(f"Saved {path}  ({len(verts)} verts, {len(faces)} faces)")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("output", nargs="?",
                    default="uploads/600mStar.obj",
                    help="Output OBJ path (default: uploads/600mStar.obj)")
    ap.add_argument("--arms",   type=int,   default=6,    help="Number of star arms (default 6)")
    ap.add_argument("--outer",  type=float, default=0.44, help="Outer tip radius mm (default 0.44)")
    ap.add_argument("--inner",  type=float, default=0.20, help="Inner concave radius mm (default 0.20)")
    ap.add_argument("--height", type=float, default=0.30, help="Extrusion height mm (default 0.30)")
    args = ap.parse_args()

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    verts, faces = build_star_prism(
        arms=args.arms,
        r_outer=args.outer,
        r_inner=args.inner,
        height=args.height,
    )

    # Compute bounding-sphere radius for info
    cx = sum(v[0] for v in verts) / len(verts)
    cy = sum(v[1] for v in verts) / len(verts)
    cz = sum(v[2] for v in verts) / len(verts)
    import math
    r = max(math.sqrt((v[0]-cx)**2+(v[1]-cy)**2+(v[2]-cz)**2) for v in verts)
    print(f"Star prism: {args.arms} arms, r_outer={args.outer}, r_inner={args.inner}, h={args.height}")
    print(f"Bounding-sphere radius ~ {r:.4f} mm")

    save_obj(str(out), verts, faces)


if __name__ == "__main__":
    main()
